services:
  backend:
    image: eclipse-temurin:17-jdk
    container_name: spring-backend
    working_dir: /app

    ports:
      - "8080:8080"

    volumes:
      - ./backend:/app
      - maven-cache:/root/.m2

    command: ./mvnw spring-boot:run

    environment:
      SPRING_PROFILES_ACTIVE: dev

  frontend:
    image: node:20-alpine
    container_name: react-frontend
    working_dir: /app

    ports:
      - "5173:5173"

    volumes:
      - ./frontend:/app
      - node-modules:/app/node_modules

    command: sh -c "npm install && npm run dev"

    environment:
      CHOKIDAR_USEPOLLING: "true"

    depends_on:
      - backend

volumes:
  maven-cache:
  node-modules:
